#baseURL = "https://unixmagic.net/"
baseURL = "/"
relativeURLs = true
uglyURLs = false
languageCode = "en-us"
title = "Unix Magic Poster Annotations"
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


