baseURL = "https://drio.github.io/unixmagic/"
languageCode = "en-us"
title = "Unix Poster Annotations"
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


